apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-demo
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  POSTGRES_PASSWORD: reaction_game
  # Optional RSA paths inside containers.
  # If you mount keys as files, set these paths and switch SECURITY_RSA_VERIFY_REQUIRED to 1.
  UPDATER_RSA_PRIVATE_KEY_PATH: ""
  SECURITY_RSA_PUBLIC_KEY_PATH: ""
